# fly.toml app configuration file generated for telegramm-bot-red-hill-5336 on 2025-03-10T00:35:56+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'telegramm-bot-red-hill-5336'
primary_region = 'fra'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  release_command = 'python bot.py'

[env]
  PORT = '8080'

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  auto_stop_machines = 'off'
  auto_start_machines = true

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
